name: databricks-digital-twin
description: "Databricks Digital Twin - Manufacturing RDF Visualization Platform with Real-time Telemetry"

# App configuration
kind: app
image: python:3.11

# Environment variables
environment:
  - name: FLASK_APP
    value: app.py
  - name: FLASK_ENV
    value: production
  - name: PYTHONPATH
    value: /app
  - name: PORT
    value: "8080"

# Application endpoints
endpoints:
  - name: main
    port: 8080

# Startup command
command:
  - python
  - app.py

# Resource configuration
resources:
  cpu: "1000m"
  memory: "2Gi"

# Health check
health_check:
  path: "/"
  port: 8080
  initial_delay_seconds: 30
  period_seconds: 10

# Static file serving for both frontends
static_files:
  # Main React frontend
  - url: "/"
    directory: "dist"
    fallback: "dist/index.html"

  # Vue graph visualizer
  - url: "/visualiser"
    directory: "dist/visualiser"
    fallback: "dist/visualiser/index.html"

  # Static assets
  - url: "/static"
    directory: "dist/static"

  # API endpoints (handled by Flask)
  - url: "/api"
    directory: ""  # Will be handled by Flask backend

# File includes for deployment
includes:
  - "**/*.py"
  - "**/*.html"
  - "**/*.js"
  - "**/*.css"
  - "**/*.json"
  - "**/*.ttl"
  - "requirements.txt"
  - "dist/**/*"
  - "example-ttls/**/*"

# File excludes
excludes:
  - "**/__pycache__/**"
  - "**/*.pyc"
  - "**/node_modules/**"
  - "**/.git/**"
  - "**/.env.local"
  - "**/venv/**"
  - "**/.pytest_cache/**"